#### Web Scraping Movie data

In [1]:
from requests import get

In [2]:
url = "https://www.imdb.com/list/ls062559851/" #2017

url2 = "https://www.imdb.com/list/ls034587282/" #2016

In [3]:
response = get(url)
print(response)

response2 = get(url2)
print(response2)

<Response [200]>
<Response [200]>

In [4]:
from bs4 import BeautifulSoup as bs ## importing Beautiful Soup

html_soup = bs(response.text,'html.parser')# python's in built library HTML parser
print(type(html_soup))

html_soup2 = bs(response2.text,'html.parser')
print(type(html_soup2))

<class 'bs4.BeautifulSoup'>
<class 'bs4.BeautifulSoup'>

In [5]:
id_check = html_soup.find(id ="main")
movie_container = id_check.find_all(class_ ="lister-item mode-detail")
print(len(movie_container))

id_check2 = html_soup2.find(id="main")
movie_container2 = id_check2.find_all(class_="lister-item mode-detail")
print(len(movie_container))

20
20

In [8]:
#Scraping 2017
movie_names = []
year_release = []
imdb_ratings = []
metascores = []
votes = []
movie_description = []
certificate = []
runtime = []
genre = []
director_name = []
star_cast = []
gross_value = []

#extract data from individual movie container
for container in movie_container:
    
   
    #if movie has Metascore, then extract:
    if container.find("div", class_ = "ratings-metascore") is not None:
        
        
        #the movie_name
        name = container.h3.a.text
        movie_names.append(name)
        
        #the year od release
        release = container.find("span", class_ = "lister-item-year text-muted unbold").text
        year_release.append(release)
        
       
        
        #the genre
        gen = container.find("span", class_ ="genre").text
        genre.append(gen)
        #fetching all <p> tags
        content = container.find_all("p")
        
        
        #subsetting all the <a> tags in 3rd <p> tag
        content_2 = content[2].find_all("a")
        
        #the director
        director = content_2[0].text
        director_name.append(director)
        
        #the gross value
        if len(container.find_all("span", attrs = {"name":"nv"})) >= 2:
            gross = container.find_all("span", attrs = {"name":"nv"})[1]['data-value']
            gross_value.append(gross)
        else:
            gross_value.append(None)
        #extracting artists names
        temp = []
        for i in range(len(content_2)-1):
            temp.append(content_2[i].text)
        star_cast.append(temp)

In [9]:
#Scraping 2016

movie_names2 = []
year_release2 = []
imdb_ratings2 = []
metascores2 = []
votes2 = []
movie_description2 = []
certificate2 = []
runtime2 = []
genre2 = []
director_name2 = []
star_cast2 = []
gross_value2 = []

#extract data from individual movie container
for container in movie_container2:
    
   
    #if movie has Metascore, then extract:
    if container.find("div", class_ = "ratings-metascore") is not None:
        
        
        #the movie_name
        name = container.h3.a.text
        movie_names2.append(name)
        
        #the year od release
        release = container.find("span", class_ = "lister-item-year text-muted unbold").text
        year_release2.append(release)
        
       
        
        #the genre
        gen = container.find("span", class_ ="genre").text
        genre2.append(gen)
        #fetching all <p> tags
        content = container.find_all("p")
        
        
        #subsetting all the <a> tags in 3rd <p> tag
        content_2 = content[2].find_all("a")
        
        #the director
        director = content_2[0].text
        director_name2.append(director)
        
        #the gross value
        if len(container.find_all("span", attrs = {"name":"nv"})) >= 2:
            gross = container.find_all("span", attrs = {"name":"nv"})[1]['data-value']
            gross_value2.append(gross)
        else:
            gross_value2.append(None)
        #extracting artists names
        temp = []
        for i in range(len(content_2)-1):
            temp.append(content_2[i].text)
        star_cast2.append(temp)

In [10]:
#Cleaning genre list
print(genre)
print()
g_list1_2017 = [s.strip("      ") for s in genre]
print(g_list1_2017)
print()


g_list1_2016 = [s.strip("      ") for s in genre2]
print(g_list1_2016)
print()

['\nAction, Adventure, Fantasy            ', '\nAction, Crime, Drama            ', '\nBiography, Drama, History            ', '\nAction, Drama, Sci-Fi            ', '\nAnimation, Drama, Fantasy            ', '\nAction, Crime, Thriller            ', '\nHorror, Mystery, Thriller            ', '\nAnimation, Fantasy            ', '\nComedy, Drama, Music            ', '\nAction, Adventure, Comedy            ', '\nDrama            ', '\nBiography, Drama, Romance            ', '\nDrama            ', '\nAnimation, Comedy, Family            ', '\nDrama            ', '\nAction, Adventure, Comedy            ', '\nAnimation, Action, Comedy            ', '\nBiography, Drama, History            ', '\nBiography, Drama, History            ']

['\nAction, Adventure, Fantasy', '\nAction, Crime, Drama', '\nBiography, Drama, History', '\nAction, Drama, Sci-Fi', '\nAnimation, Drama, Fantasy', '\nAction, Crime, Thriller', '\nHorror, Mystery, Thriller', '\nAnimation, Fantasy', '\nComedy, Drama, Music', '\nAction, Adventure, Comedy', '\nDrama', '\nBiography, Drama, Romance', '\nDrama', '\nAnimation, Comedy, Family', '\nDrama', '\nAction, Adventure, Comedy', '\nAnimation, Action, Comedy', '\nBiography, Drama, History', '\nBiography, Drama, History']

['\nComedy, Drama, Music', '\nDrama, Mystery, Romance', '\nDrama, Romance, Thriller', '\nDrama, Romance', '\nCrime, Drama, Thriller', '\nAdventure, Drama, Romance', '\nCrime, Drama', '\nDrama, Horror, Mystery', '\nComedy, Drama', '\nBiography, Drama, History', '\nDrama', '\nDrama, Mystery, Romance', '\nComedy, Drama, Music', '\nAction, Adventure, Crime', '\nAnimation, Drama, Fantasy', '\nComedy, Drama, Romance', '\nAnimation, Adventure, Comedy', '\nDrama, Thriller']

In [11]:
g_list2_2017 = [s.strip("\n") for s in g_list1_2017]
print(g_list2_2017)
print()

g_list2_2016 = [s.strip("\n") for s in g_list1_2016]
print(g_list2_2016)

['Action, Adventure, Fantasy', 'Action, Crime, Drama', 'Biography, Drama, History', 'Action, Drama, Sci-Fi', 'Animation, Drama, Fantasy', 'Action, Crime, Thriller', 'Horror, Mystery, Thriller', 'Animation, Fantasy', 'Comedy, Drama, Music', 'Action, Adventure, Comedy', 'Drama', 'Biography, Drama, Romance', 'Drama', 'Animation, Comedy, Family', 'Drama', 'Action, Adventure, Comedy', 'Animation, Action, Comedy', 'Biography, Drama, History', 'Biography, Drama, History']

['Comedy, Drama, Music', 'Drama, Mystery, Romance', 'Drama, Romance, Thriller', 'Drama, Romance', 'Crime, Drama, Thriller', 'Adventure, Drama, Romance', 'Crime, Drama', 'Drama, Horror, Mystery', 'Comedy, Drama', 'Biography, Drama, History', 'Drama', 'Drama, Mystery, Romance', 'Comedy, Drama, Music', 'Action, Adventure, Crime', 'Animation, Drama, Fantasy', 'Comedy, Drama, Romance', 'Animation, Adventure, Comedy', 'Drama, Thriller']

In [12]:
#cleaning year and changing it to int type

list1_2017 = [s.strip(')') for s in year_release]
list1_2016 = [s.strip(')') for s in year_release2]
#print(list1_2017)
#print()
#print(list1_2016)

In [13]:
list2_2017 =  [s.strip('(') for s in list1_2017]
list2_2016 =  [s.strip('(') for s in list1_2016]

print(list2_2017)
print()
print(list2_2016)

['2017', '2017', '2016', '2017', '2016', '2017', 'I) (2017', '2016', 'I) (2016', '2017', 'I) (2016', '2016', '2016', '2016', '2016', '2017', '2017', '2016', '2016']

['I) (2015', '2016', '2016', 'II) (2015', 'I) (2016', '2016', '2015', '2016', '2015', '2016', '2015', '2016', '2016', 'I) (2016', '2016', '2015', '2016', 'I) (2015']

In [14]:
list3_2017 = [s.strip(" 'I) ") for s in list2_2017]
list3_2016 = [s.strip(" 'I) ") for s in list2_2016]
print(list3_2017)
print(len(list3_2017))
print()

print(list3_2016)
print(len(list3_2016))
print()

['2017', '2017', '2016', '2017', '2016', '2017', '(2017', '2016', '(2016', '2017', '(2016', '2016', '2016', '2016', '2016', '2017', '2017', '2016', '2016']
19

['(2015', '2016', '2016', '(2015', '(2016', '2016', '2015', '2016', '2015', '2016', '2015', '2016', '2016', '(2016', '2016', '2015', '2016', '(2015']
18

In [15]:
list4_2017 = [s.strip(" '(") for s in list3_2017]
list4_2016 = [s.strip(" '(") for s in list3_2016]
print(list4_2017)
print()
print(len(list4_2017))

print(list4_2016)
print()
print(len(list4_2016))

['2017', '2017', '2016', '2017', '2016', '2017', '2017', '2016', '2016', '2017', '2016', '2016', '2016', '2016', '2016', '2017', '2017', '2016', '2016']

19
['2015', '2016', '2016', '2015', '2016', '2016', '2015', '2016', '2015', '2016', '2015', '2016', '2016', '2016', '2016', '2015', '2016', '2015']

18

In [16]:
#Convert String to int type

for i in range(0,19):
    string_value = list4_2017[i]
    int_value = int(string_value)
    list4_2017[i] = int_value
print(list4_2017)
print()
print(len(list4_2017))

for i in range(0,18):
    string_value2 = list4_2016[i]
    int_value2 = int(string_value2)
    list4_2016[i] = int_value2
print(list4_2016)
print()
print(len(list4_2016))

[2017, 2017, 2016, 2017, 2016, 2017, 2017, 2016, 2016, 2017, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2016, 2016]

19
[2015, 2016, 2016, 2015, 2016, 2016, 2015, 2016, 2015, 2016, 2015, 2016, 2016, 2016, 2016, 2015, 2016, 2015]

18

In [17]:
director_twitter_handle_2017 = ['rianjohnson','edgarwright','theodoremelfi','mang0ld','FilmBayona','','JordanPeele',
                 '','DSChazelle','','BarryJenkins','','OfficiaIDenzeI','GarthJennings','',
                 'JamesGunn','buddboetticher','','']
print(len(director_twitter_handle_2017))
print()


director_twitter_handle_2016=['paolosorren','iwaishunji','','','VerhoevensTweet','drearnold',
                              '','creepypuppet','ANNAMUYLAERT','','','TodoAlmodovar','jayceefactory','HenryJoost',
                              'shinkaimakoto','','ByronPHoward','lennyabrahamson']
print(len(director_twitter_handle_2016))

19

18

In [18]:
company_list = ['Lucas Film','Working Title Films','20th Century Fox','20th Century Fox','Participant Media',
                'Summit Entertainment','Blumhouse Productions','Studio Ghibli','Summit Entertainment','Marv Films',
                'A24','Big Beach','Paramount Pictures','Illumination Entertainment','K period Media',
                'Marvel Studios','Warner Animation Group','FilmNation Entertainment','Icon Productions','Indigo Film',
                'Toei Company','Moho Film','Wild Bunch','Canal+','British Film Institute',
                'Why Not Productions','New Line Cinema','Globo Filmes','Icon Productions','CG Cinéma',
                'El Deseo','Likely Story','Allison Shearmur Productions','CoMix Wave','Archer Gray Productions',
                'Walt Disney Animation','Element Pictures']
print(len(company_list))

company_twitter_list = ['','Working_Title','20thcenturyfox','20thcenturyfox','Participant',
                        'SummitEnt','blumhouse','','SummitEnt','',
                        'A24','BigBeachFilms','ParamountPics','IllumEnt','KPeriodMedia',
                        'MarvelStudios','WarnerBrosEnt','filmnation','IconFilms','indigo_film',
                        'TOEI_PR','moho_animation','WildBunch','canalplus','BFI',
                        'whynotprod','newlinecinema','GloboFilmes','IconFilms','',
                        'eldeseo','likelystory_mcr','','','Archer_Gray',
                        'DisneyAnimation','ElementPictures']
len(company_twitter_list)

37

37

In [19]:
final_movie_name = movie_names + movie_names2
final_year = list4_2017  + list4_2016
final_genre = g_list2_2017 + g_list2_2016
final_director = director_name + director_name2
final_gross = gross_value + gross_value2
final_twitter = director_twitter_handle_2017 + director_twitter_handle_2016

In [20]:
import pandas as pd

In [21]:
frame_final = pd.DataFrame({"Movie":final_movie_name,
                           "Year":final_year,
                           "Genre":final_genre,
                           "D_name":final_director,
                            "username_d":final_twitter,
                            "PC_name":company_list,
                            "username_pc":company_twitter_list
                           })
frame_final.index = frame_final.index + 1

In [22]:
import numpy as np
frame_final.replace('', np.nan, inplace=True)


frame_final

,Movie,Year,Genre,D_name,username_d,PC_name,username_pc
1,Star Wars: Episode VIII - The Last Jedi,2017,"Action, Adventure, Fantasy",Rian Johnson,rianjohnson,Lucas Film,NaN
2,Baby Driver,2017,"Action, Crime, Drama",Edgar Wright,edgarwright,Working Title Films,Working_Title
3,Hidden Figures,2016,"Biography, Drama, History",Theodore Melfi,theodoremelfi,20th Century Fox,20thcenturyfox
4,Logan,2017,"Action, Drama, Sci-Fi",James Mangold,mang0ld,20th Century Fox,20thcenturyfox
5,A Monster Calls,2016,"Animation, Drama, Fantasy",J.A. Bayona,FilmBayona,Participant Media,Participant
6,John Wick: Chapter 2,2017,"Action, Crime, Thriller",Chad Stahelski,NaN,Summit Entertainment,SummitEnt
7,Get Out,2017,"Horror, Mystery, Thriller",Jordan Peele,JordanPeele,Blumhouse Productions,blumhouse
8,La tortue rouge,2016,"Animation, Fantasy",Michael Dudok de Wit,NaN,Studio Ghibli,NaN
9,La La Land,2016,"Comedy, Drama, Music",Damien Chazelle,DSChazelle,Summit Entertainment,SummitEnt
10,Kingsman: The Golden Circle,2017,"Action, Adventure, Comedy",Matthew Vaughn,NaN,Marv Films,NaN
11,Moonlight,2016,Drama,Barry Jenkins,BarryJenkins,A24,A24
12,Loving,2016,"Biography, Drama, Romance",Jeff Nichols,NaN,Big Beach,BigBeachFilms
13,Fences,2016,Drama,Denzel Washington,OfficiaIDenzeI,Paramount Pictures,ParamountPics
14,Sing,2016,"Animation, Comedy, Family",Garth Jennings,GarthJennings,Illumination Entertainment,IllumEnt
15,Manchester by the Sea,2016,Drama,Kenneth Lonergan,NaN,K period Media,KPeriodMedia
16,Guardians of the Galaxy Vol. 2,2017,"Action, Adventure, Comedy",James Gunn,JamesGunn,Marvel Studios,MarvelStudios
17,The Lego Batman Movie,2017,"Animation, Action, Comedy",Chris McKay,buddboetticher,Warner Animation Group,WarnerBrosEnt
18,The Founder,2016,"Biography, Drama, History",John Lee Hancock,NaN,FilmNation Entertainment,filmnation
19,Hacksaw Ridge,2016,"Biography, Drama, History",Mel Gibson,NaN,Icon Productions,IconFilms
20,Youth,2015,"Comedy, Drama, Music",Paolo Sorrentino,paolosorren,Indigo Film,indigo_film
21,Rippu Van Winkuru no hanayome,2016,"Drama, Mystery, Romance",Shunji Iwai,iwaishunji,Toei Company,TOEI_PR
22,The Handmaiden,2016,"Drama, Romance, Thriller",Chan-wook Park,NaN,Moho Film,moho_animation
23,Love,2015,"Drama, Romance",Gaspar Noé,NaN,Wild Bunch,WildBunch
24,Elle,2016,"Crime, Drama, Thriller",Paul Verhoeven,VerhoevensTweet,Canal+,canalplus
25,American Honey,2016,"Adventure, Drama, Romance",Andrea Arnold,drearnold,British Film Institute,BFI
26,Dheepan,2015,"Crime, Drama",Jacques Audiard,NaN,Why Not Productions,whynotprod
27,The Conjuring 2,2016,"Drama, Horror, Mystery",James Wan,creepypuppet,New Line Cinema,newlinecinema
28,Que Horas Ela Volta?,2015,"Comedy, Drama",Anna Muylaert,ANNAMUYLAERT,Globo Filmes,GloboFilmes
29,Hacksaw Ridge,2016,"Biography, Drama, History",Mel Gibson,NaN,Icon Productions,IconFilms
30,Mustang,2015,Drama,Deniz Gamze Ergüven,NaN,CG Cinéma,NaN
31,Julieta,2016,"Drama, Mystery, Romance",Pedro Almodóvar,TodoAlmodovar,El Deseo,eldeseo
32,Sing Street,2016,"Comedy, Drama, Music",John Carney,jayceefactory,Likely Story,likelystory_mcr
33,Nerve,2016,"Action, Adventure, Crime",Henry Joost,HenryJoost,Allison Shearmur Productions,NaN
34,Your Name.,2016,"Animation, Drama, Fantasy",Makoto Shinkai,shinkaimakoto,CoMix Wave,NaN
35,The Diary of a Teenage Girl,2015,"Comedy, Drama, Romance",Marielle Heller,NaN,Archer Gray Productions,Archer_Gray
36,Zootopia,2016,"Animation, Adventure, Comedy",Byron Howard,ByronPHoward,Walt Disney Animation,DisneyAnimation
37,Room,2015,"Drama, Thriller",Lenny Abrahamson,lennyabrahamson,Element Pictures,ElementPictures

In [23]:
frame_final.isnull().sum()

Movie           0
Year            0
Genre           0
D_name          0
username_d     13
PC_name         0
username_pc     6
dtype: int64

## Social Media API - Twitter

### Authentication

In [88]:
import twitter # pip install twitter
import csv
import json
import tweepy #pip install tweepy
import pandas

In [89]:
consumer_key = '*****'
consumer_secret = '*****'
access_token = '****-****'
access_token_secret = '********'
    
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)

### Director's Twitter Account Data

In [90]:
director_twitter = ['rianjohnson','edgarwright','theodoremelfi','mang0ld','FilmBayona','JordanPeele',
                    'DSChazelle','BarryJenkins','OfficiaIDenzeI','GarthJennings',
                    'JamesGunn','buddboetticher','paolosorren','iwaishunji','VerhoevensTweet','drearnold',
                    'ANNAMUYLAERT','TodoAlmodovar','jayceefactory','HenryJoost',
                    'shinkaimakoto','ByronPHoward','lennyabrahamson']

In [91]:
username_list=[]
name_list=[]
tweet_count_list=[]
following_count_list=[]
followers_count_list=[]

In [92]:
account_name_list = director_twitter
num = len(account_name_list)

In [93]:
for i in range(num):
    print(i)
    print(account_name_list[i])
    print()
    
    item = api.get_user(account_name_list[i])
    
    account_username = item.screen_name
    account_name = item.name
    account_description = item.description
    account_tweet_count = item.statuses_count
    account_following = item.friends_count
    account_followers = item.followers_count
    
    name_list.append(account_name)
    username_list.append(account_username)
    tweet_count_list.append(account_tweet_count)
    following_count_list.append(account_following)
    followers_count_list.append(account_followers)

print(name_list)
#print(username_list)
#print(tweet_count_list)
#print(following_count_list)
#print(followers_count_list)

0
rianjohnson

1
edgarwright

2
theodoremelfi

3
mang0ld

4
FilmBayona

5
JordanPeele

6
DSChazelle

7
BarryJenkins

8
OfficiaIDenzeI

9
GarthJennings

10
JamesGunn

11
buddboetticher

12
paolosorren

13
iwaishunji

14
VerhoevensTweet

15
drearnold

16
ANNAMUYLAERT

17
TodoAlmodovar

18
jayceefactory

19
HenryJoost

20
shinkaimakoto

21
ByronPHoward

22
lennyabrahamson

['Rian Johnson', 'edgarwright', 'Theodore Melfi', 'Mangold', 'JA Bayona', 'Jordan Peele', 'Damien Chazelle', 'Barry Jenkins', 'Denzel Washington', 'Garth Jennings', 'James Gunn', 'Chris McKay', 'Paolo Sorrentino', 'iwai shunji', 'Paul Verhoeven', 'Andrea Arnold', 'anna', 'Todo Pedro Almodóvar', 'John Carney', 'Henry Joost', '新海誠', 'Byron Howard', 'lenny abrahamson']

### Production Companies' Twitter Account Data

In [94]:
company_twitter = ['Working_Title','20thcenturyfox','20thcenturyfox','Participant',
                        'SummitEnt','blumhouse','SummitEnt',
                        'A24','BigBeachFilms','ParamountPics','IllumEnt','KPeriodMedia',
                        'MarvelStudios','WarnerBrosEnt','filmnation','IconFilms','indigo_film',
                        'TOEI_PR','moho_animation','WildBunch','canalplus','BFI',
                        'whynotprod','newlinecinema','GloboFilmes','IconFilms',
                        'eldeseo','likelystory_mcr','Archer_Gray',
                        'DisneyAnimation','ElementPictures']

In [95]:
pc_username_list=[]
pc_name_list=[]
pc_tweet_count_list=[]
pc_following_count_list=[]
pc_followers_count_list=[]

In [96]:
account_name_list = company_twitter
num = len(account_name_list)

In [97]:
for i in range(num):
    #print(i)
    #print(account_name_list[i])
    #print()
    
    item = api.get_user(account_name_list[i])
    
    account_username = item.screen_name
    account_name = item.name
    account_description = item.description
    account_tweet_count = item.statuses_count
    account_following = item.friends_count
    account_followers = item.followers_count
    
    pc_name_list.append(account_name)
    pc_username_list.append(account_username)
    pc_tweet_count_list.append(account_tweet_count)
    pc_following_count_list.append(account_following)
    pc_followers_count_list.append(account_followers)

#print(name_list)
#print(username_list)
#print(tweet_count_list)
#print(following_count_list)
#print(followers_count_list)

####  Directors - twitter account - Dataframe

In [98]:
frame_account_data_d = pandas.DataFrame(data={'D_Name':name_list,'username_d':username_list,'Total_Tweets':tweet_count_list,
                                            'Following':following_count_list,'Followers':followers_count_list})
frame_account_data_d.index = frame_account_data_d.index + 1

####  Production Company - twitter account - Dataframe

In [99]:
frame_account_data_pc = pandas.DataFrame(data={'PC_Name':pc_name_list,'username_pc':pc_username_list,'Total_Tweets':pc_tweet_count_list,
                                            'Following':pc_following_count_list,'Followers':pc_followers_count_list})
frame_account_data_pc.index = frame_account_data_pc.index + 1

In [100]:
frame_account_data_d

                  D_Name       username_d  Total_Tweets  Following  Followers
1           Rian Johnson      rianjohnson          2069       1085     944163
2            edgarwright      edgarwright         34683       3564     779789
3         Theodore Melfi    theodoremelfi          8731        142       3379
4                Mangold          mang0ld          5624        474      63616
5              JA Bayona       FilmBayona          9381        789     175311
6           Jordan Peele      JordanPeele          4116       1584    1431539
7        Damien Chazelle       DSChazelle            67         89      35774
8          Barry Jenkins     BarryJenkins          7677       2539     177033
9      Denzel Washington   OfficiaIDenzeI            87          0      18877
10        Garth Jennings    GarthJennings          2051        256       6643
11            James Gunn        JamesGunn         20468        869     586581
12           Chris McKay   buddboetticher          2874       2973      15777
13      Paolo Sorrentino      paolosorren            10         12        571
14           iwai shunji       iwaishunji            53          8        763
15        Paul Verhoeven  VerhoevensTweet           172         37      12570
16         Andrea Arnold        drearnold          1832       1743       1041
17                  anna     ANNAMUYLAERT          2724        210       4015
18  Todo Pedro Almodóvar    TodoAlmodovar          1278        803       4612
19           John Carney    jayceefactory           196        216       5021
20           Henry Joost       HenryJoost           112         13         41
21                   新海誠    shinkaimakoto          8068        388     603475
22          Byron Howard     ByronPHoward          2942        545      29476
23      lenny abrahamson  lennyabrahamson         13791       1217      38216

In [35]:
frame_account_data_pc

                 PC_Name      username_pc  Total_Tweets  Following  Followers
1          Working Title    Working_Title          2066        737      13897
2       20th Century Fox   20thcenturyfox          7120       1729    3734157
3       20th Century Fox   20thcenturyfox          7120       1729    3734157
4      Participant Media      Participant         41178       5667      90113
5   Summit Entertainment        SummitEnt          1533        209     132082
6              Blumhouse        blumhouse         17459       1778     205586
7   Summit Entertainment        SummitEnt          1533        209     132082
8                    A24              A24          5758       1070    1458788
9              Big Beach    BigBeachFilms           753        571       2208
10    Paramount Pictures    ParamountPics          9247       9353    2825272
11     Illumination Ent.         IllumEnt           268         18       2484
12        K Period Media     KPeriodMedia            37         76        167
13        Marvel Studios    MarvelStudios          9463         81    2135706
14          Warner Bros.    WarnerBrosEnt          8065        296    2033522
15            FilmNation       filmnation          3833        379       7508
16            Icon Films        IconFilms          4991        661      12973
17           Indigo Film      indigo_film          1676        479       6431
18              東映公式ニュース          TOEI_PR          7963        251      46810
19  Moho® (Anime Studio)   moho_animation          4630       4194       5721
20          Wild Bunch 🐉        WildBunch         14641       2020      39127
21                CANAL+        canalplus         61371       1025    3015780
22                   BFI              BFI         61481       2624     820329
23   Why Not Productions       whynotprod            53        252        624
24       New Line Cinema    newlinecinema          1821        418      16563
25          Globo Filmes      GloboFilmes          9033        313      39932
26            Icon Films        IconFilms          4991        661      12973
27              el deseo          eldeseo          2835        308      38476
28          Likely Story  likelystory_mcr            68        272        352
29           Archer Gray      Archer_Gray           622        385        600
30      Disney Animation  DisneyAnimation          3613        177    3067678
31      Element Pictures  ElementPictures          4083       1644      13429

### Director - Tweet Data

In [101]:
temp_id=[]
temp_content=[]
temp_length=[]
temp_date=[]
temp_source=[]
temp_likes=[]
temp_retweets=[]
temp_list2=[]

In [102]:
screen_name_list = director_twitter
num2 = len(screen_name_list)

In [103]:
for i in range(num2):
    #print(i)
    #print(screen_name_list[i])
    #print()
    temp_screen_name = screen_name_list[i]
    number_of_tweets = 5
    tweets = api.user_timeline(screen_name = screen_name_list[i], count = number_of_tweets,tweet_mode='extended')
    
    
    tweet_id = [tweet.id for tweet in tweets]
    tweet_content = [tweet.full_text for tweet in tweets]
    tweet_length = [len(tweet.full_text) for tweet in tweets]
    tweet_date = [tweet.created_at for tweet in tweets]
    tweet_source = [tweet.source for tweet in tweets]
    tweet_likes = [tweet.favorite_count for tweet in tweets]
    tweet_retweets = [tweet.retweet_count for tweet in tweets]
    
    #To create multiple usernames
    username_list_temp = temp_screen_name
    num = number_of_tweets
    temp_list =[]
    for i in range(0,num):
        user_name_temp = temp_screen_name
        temp_list.append(user_name_temp)
    
    
    temp_id += tweet_id
    temp_content += tweet_content
    temp_length += tweet_length
    temp_date += tweet_date
    temp_source += tweet_source
    temp_likes += tweet_likes
    temp_retweets += tweet_retweets
    temp_list2 += temp_list
    
    #Print  all lists
    #print(temp_id)
    #print()
    #print(temp_content)
    #print()
    #print(temp_length)
    #print()
    #print(temp_date)
    #print()
    #print(temp_source)
    #print()
    #print(temp_likes)
    #print()
    #print(temp_retweets)
    #print()
    #print(temp_list2)
    #print()
    #print("------------------------------------------------------------------")
    #print(temp_list)
    #print()
    #print(tweet_id)
    #print()
    #print(tweet_content)
    #print()
    #print(tweet_length)
    #print()
    #print(tweet_date)
    #print()
    #print(tweet_source)
    #print()
    #print(tweet_likes)
    #print()
    #print(tweet_retweets)
    #print()
    #print("-"*20)

### Production Company - Tweet Data

In [104]:
pc_temp_id=[]
pc_temp_content=[]
pc_temp_length=[]
pc_temp_date=[]
pc_temp_source=[]
pc_temp_likes=[]
pc_temp_retweets=[]
pc_temp_list2=[]

In [105]:
screen_name_list = company_twitter
num2 = len(screen_name_list)
print(num2)

31

In [106]:
for i in range(num2):
    #print(i)
    #print(screen_name_list[i])
    #print()
    temp_screen_name = screen_name_list[i]
    number_of_tweets = 5
    tweets = api.user_timeline(screen_name = screen_name_list[i], count = number_of_tweets,tweet_mode='extended')
    
    
    tweet_id = [tweet.id for tweet in tweets]
    tweet_content = [tweet.full_text for tweet in tweets]
    tweet_length = [len(tweet.full_text) for tweet in tweets]
    tweet_date = [tweet.created_at for tweet in tweets]
    tweet_source = [tweet.source for tweet in tweets]
    tweet_likes = [tweet.favorite_count for tweet in tweets]
    tweet_retweets = [tweet.retweet_count for tweet in tweets]
    
    #To create multiple usernames
    username_list_temp = temp_screen_name
    num = number_of_tweets
    temp_list =[]
    for i in range(0,num):
        user_name_temp = temp_screen_name
        temp_list.append(user_name_temp)
    
    
    pc_temp_id += tweet_id
    pc_temp_content += tweet_content
    pc_temp_length += tweet_length
    pc_temp_date += tweet_date
    pc_temp_source += tweet_source
    pc_temp_likes += tweet_likes
    pc_temp_retweets += tweet_retweets
    pc_temp_list2 += temp_list
    
    #Print  all lists
    #print(temp_id)
    #print()
    #print(temp_content)
    #print()
    #print(temp_length)
    #print()
    #print(temp_date)
    #print()
    #print(temp_source)
    #print()
    #print(temp_likes)
    #print()
    #print(temp_retweets)
    #print()
    #print(temp_list2)
    #print()
    #print("------------------------------------------------------------------")
    #print(temp_list)
    #print()
    #print(tweet_id)
    #print()
    #print(tweet_content)
    #print()
    #print(tweet_length)
    #print()
    #print(tweet_date)
    #print()
    #print(tweet_source)
    #print()
    #print(tweet_likes)
    #print()
    #print(tweet_retweets)
    #print()
    #print("-"*20)

#### Director - Tweet Data - Dataframe

In [107]:
temp_id = str(temp_id)

In [108]:
print(len(temp_list2))
print(len(temp_id))
print(len(temp_content))
print(len(temp_date))
print(len(temp_source))
print(len(temp_likes))
print(len(temp_retweets))

115
2396
115
115
115
115
115

In [109]:
print(temp_id)

[1109166408951164928, 1109103786121818112, 1108613963871248385, 1107429248627695616, 1107171386592657415, 1109244223231012865, 1109234344089014273, 1109232710982254593, 1109226016931831808, 1109219297363193856, 1100424235661447168, 1096584047415848960, 1096186034641981440, 1095004056236388352, 1092663654464540673, 1105855222809649154, 1104639616991150081, 1104176199163494401, 1103555889007493120, 1103001030948581376, 1109038003832451072, 1108666791612563459, 1108484586961596418, 1108115204334907392, 1108095844815958016, 1109152662207893504, 1109100685172314114, 1109037654052614145, 1108915834611789825, 1108883197520166912, 1058026307177525248, 1049818217017835520, 917973092819001344, 917972361894420481, 917972278486425600, 1109219570038919168, 1109206529905876992, 1109144085963534336, 1109135746370142209, 1109129550032564225, 1107425802822537216, 1100378558772449280, 1097570730311643136, 1094950575823904769, 1094950196679708672, 1109128743950389248, 1109106593352896512, 1109022956183871488, 1108804842200412165, 1108735275209940992, 1106633508657651712, 1020154780012834816, 1020154779169783808, 1020154778356146177, 1020154777525575682, 1100702312106991617, 1099815526963036165, 1099328511687475201, 1093929362741616640, 1093756546712883200, 806288039442087937, 806288009083633664, 806287989517275136, 806287953253322752, 806287916221796352, 344570870234222592, 332993898970480640, 327001136114573313, 326999122605400064, 326998887988617216, 492174340948258816, 426020319217074176, 383656035405561856, 379660727461892096, 365364716845010945, 1086077004191952899, 1034201652033536002, 1026943713346342912, 1019339350356529152, 1017577631749771264, 1086295335692107776, 1086295131282722816, 1086294577932365825, 1086229625708208128, 1086229604526972928, 1109183108996317186, 1109037284798672897, 1108707906357219328, 1108609444387188736, 1108458759519645698, 1064519969994625024, 1064519731942752256, 1063094545846620161, 1057237788230381568, 888801486939017217, 1075110819786944512, 1069986970359685121, 1064627251092889600, 1059842724361367554, 1059558575289319428, 1109130206093074434, 1108707000790056961, 1108031849396228096, 1106578626906976256, 1105119183757467649, 1108618800901939200, 1108080191912316928, 1105531188846911488, 1105512374818074624, 1103186538693779456, 1109218837856169985, 1109165234374299649, 1109029948080168960, 1108898426199179264, 1108889213293027328]

In [64]:
frame_tweet_data_d = pandas.DataFrame(data={'username_d':temp_list2,'Tweet_ID':temp_id,'Tweet':temp_content,'Length':temp_length,
                                               'Tweet_Date':temp_date,
                                         'Platform':temp_source,'Favourites':temp_likes,
                                          'Retweets':temp_retweets})
    
    
frame_tweet_data_d.index = frame_tweet_data_d.index + 1

ValueError: arrays must all be same length

### Production Company - Tweet Data - Dataframe

In [43]:
print(len(pc_temp_list2))
print(len(pc_temp_id))
print(len(pc_temp_content))
print(len(pc_temp_date))
print(len(pc_temp_source))
print(len(pc_temp_likes))
print(len(pc_temp_retweets))

155
155
155
155
155
155
155

In [44]:
frame_tweet_data_pc = pandas.DataFrame(data={'username_pc':pc_temp_list2,'Tweet_ID':pc_temp_id,'Tweet':pc_temp_content,
                                             'Length':pc_temp_length,
                                               'Tweet_Date':pc_temp_date,
                                         'Platform':pc_temp_source,'Favourites':pc_temp_likes,
                                          'Retweets':pc_temp_retweets})
    
frame_tweet_data_pc.index = frame_tweet_data_pc.index + 1

### Director - Tweet Data - Dataframe

In [45]:
frame_tweet_data_d

,username_d,Tweet_ID,Tweet,Length,Tweet_Date,Platform,Favourites,Retweets
1,rianjohnson,1103152044272021506,@MarcW @clmazin @davidkwong @shannonwoodward @...,153,2019-03-06 04:35:17,Twitter for iPhone,15,1
2,rianjohnson,1102673945034022912,RT @gemko: 1985 audiences getting decidedly mi...,83,2019-03-04 20:55:29,Twitter for iPhone,0,38
3,rianjohnson,1102593471993401345,@Josh_Small God I don’t think I could pick one,46,2019-03-04 15:35:43,Twitter for iPhone,3,0
4,rianjohnson,1102589787406397440,🐶 👃 💀 🔥 👍🏻 https://t.co/IOLZiz9G0Z,34,2019-03-04 15:21:05,Twitter for iPhone,140,4
5,rianjohnson,1102389931031158785,"@thatianclay Yeah wow, they had one of those i...",147,2019-03-04 02:06:55,Twitter for iPhone,44,0
6,edgarwright,1103112720327442432,RT @lynnsheltonfilm: I'm so excited to be prem...,140,2019-03-06 01:59:02,Twitter for iPhone,0,11
7,edgarwright,1103087860297609217,RT @HillaryClinton: https://t.co/nK9t5Voc6K,43,2019-03-06 00:20:14,Twitter for iPhone,0,62514
8,edgarwright,1102924169056927744,RT @pipmadeley: This Time With Alan Partridge ...,120,2019-03-05 13:29:47,Twitter Web Client,0,177
9,edgarwright,1102899859638505473,I had both of these on audio cassette and wore...,80,2019-03-05 11:53:12,Twitter Web Client,272,7
10,edgarwright,1102705513328893953,RT @joss: The first time I met Luke Perry we t...,140,2019-03-04 23:00:56,Twitter Web Client,0,3604
11,theodoremelfi,1100424235661447168,@stevethelegend I’m trying to find it. See if ...,118,2019-02-26 15:55:57,Twitter for iPhone,2,1
12,theodoremelfi,1096584047415848960,"RT @NASAhistory: #OTD 2 years ago (Feb 15, 201...",140,2019-02-16 01:36:25,Twitter for iPhone,0,15
13,theodoremelfi,1096186034641981440,Here's a surprise: Glyphosate weed killers inc...,106,2019-02-14 23:14:51,Twitter Web Client,2,1
14,theodoremelfi,1095004056236388352,@prezcannady @kmbecker You’re so kind. Hope yo...,64,2019-02-11 16:58:05,Twitter for iPhone,2,0
15,theodoremelfi,1092663654464540673,Katey Sagal has always been a revelation. http...,65,2019-02-05 05:58:10,Twitter for iPhone,15,0
16,mang0ld,1103001030948581376,"@AgainstAllGods CB is a great artist, a great ...",92,2019-03-05 18:35:13,Twitter Web Client,23,6
17,mang0ld,1102997494504448000,RT @robertpatrickT2: COPLAND written and direc...,140,2019-03-05 18:21:10,Twitter Web Client,0,11
18,mang0ld,1102985692697653248,"RT @Kloppholic: All hail Kubrick’s, ‘Barry Lyn...",140,2019-03-05 17:34:16,Twitter Web Client,0,48
19,mang0ld,1102985623625850880,RT @Kloppholic: Filming ‘Barry Lyndon’ (1975)....,92,2019-03-05 17:33:59,Twitter Web Client,0,243
20,mang0ld,1102836351014060033,RT @Kloppholic: “Happiness isn’t something you...,140,2019-03-05 07:40:50,Twitter for iPhone,0,201
21,FilmBayona,1103317193935204355,RT @elpais_cultura: Un fenómeno editorial se r...,140,2019-03-06 15:31:32,Twitter for iPhone,0,16
22,FilmBayona,1103025368523509760,RT @movieposterguy: I love @FilmBayona’s use o...,140,2019-03-05 20:11:55,Twitter for iPhone,0,26
23,FilmBayona,1103011823253635076,Nolan: “My memories are not just of the films ...,272,2019-03-05 19:18:06,Twitter for iPhone,121,26
24,FilmBayona,1102994271207153664,RT @RubenSanchezTW: Cuando acabas de despertar...,96,2019-03-05 18:08:21,Twitter for iPhone,0,4646
25,FilmBayona,1102983324241485824,Masterpiece. https://t.co/BnD44qgwNM,36,2019-03-05 17:24:51,Twitter for iPhone,37,1
26,JordanPeele,1103362216487612416,RT @ErikDavis: They got #Us taking over Times ...,122,2019-03-06 18:30:26,Twitter for iPhone,0,127
27,JordanPeele,1102966170431307776,RT @ChocCityComics: So to celebrate @JordanPee...,140,2019-03-05 16:16:41,Twitter for iPhone,0,362
28,JordanPeele,1102766466527420416,RT @TheTwilightZone: Warning: This video cause...,111,2019-03-05 03:03:08,Twitter for iPhone,0,589
29,JordanPeele,1102689089407541248,Wow. https://t.co/b0exqrqBAu,28,2019-03-04 21:55:40,Twitter for iPhone,1615,174
30,JordanPeele,1102661659733065728,RT @iFrankAbney: 108% Funded!!!\n\nI am FLOORE...,140,2019-03-04 20:06:40,Twitter for iPhone,0,44
...,...,...,...,...,...,...,...,...
91,TodoAlmodovar,1103306028123344896,"Este domingo 10, a las 22:25 en La 2 de TVE, V...",215,2019-03-06 14:47:10,Twitter for iPhone,28,7
92,TodoAlmodovar,1103243060316700672,"Nuevas imágenes de #DolorYGloria, con Antonio ...",181,2019-03-06 10:36:57,Twitter Web Client,40,9
93,TodoAlmodovar,1103059069252841472,RT @rosaliavt: El 22 de marzo se estrena “Dolo...,140,2019-03-05 22:25:50,Twitter for iPhone,0,296
94,TodoAlmodovar,1102618258224623621,RT @sonypictures_es: Magníficas y emocionantes...,138,2019-03-04 17:14:13,Twitter for iPhone,0,8
95,TodoAlmodovar,1102530092054519810,"Este domingo 10, Versión Española emite #TodoS...",180,2019-03-04 11:23:52,Twitter for iPhone,77,17
96,jayceefactory,1064519969994625024,RT @Pidge: The hellscape that is Copenhagen tr...,140,2018-11-19 14:05:13,Twitter for iPhone,0,1268
97,jayceefactory,1064519731942752256,@HappyNenna @adamlevine @SingStreetMovie Thank...,79,2018-11-19 14:04:16,Twitter for iPhone,1,0
98,jayceefactory,1063094545846620161,"@JuddApatow A copy of Once, where he buys her ...",54,2018-11-15 15:41:05,Twitter for iPhone,24,1
99,jayceefactory,1057237788230381568,@CllrKRedmond @EamonDelaney10 H,31,2018-10-30 11:48:25,Twitter for iPhone,1,0
100,jayceefactory,888801486939017217,Richard Feynman - Wikipedia https://t.co/wMAJi...,51,2017-07-22 16:42:42,Twitter for iPhone,12,0
101,HenryJoost,1075110819786944512,Without a doubt the greatest set visit ever fr...,122,2018-12-18 19:29:28,Instagram,0,0
102,HenryJoost,1069986970359685121,Casey’s big break on Untitled Henry &amp; Rel ...,84,2018-12-04 16:09:07,Instagram,0,0
103,HenryJoost,1064627251092889600,Fantastic Mr. Foxx https://t.co/aN1gWawwhs,42,2018-11-19 21:11:31,Instagram,0,0
104,HenryJoost,1059842724361367554,VOTE | video by @rowlsonhall and @airmia22 w 1...,101,2018-11-06 16:19:31,Instagram,1,1
105,HenryJoost,1059558575289319428,Very proud of my girl!! Today she is making he...,111,2018-11-05 21:30:24,Instagram,3,0
106,shinkaimakoto,1103315083755581446,今日の帰り道では７行書けました。笑\n外は春の雨ですね。皆さんもいちにちおつかれさまでしたー...,70,2019-03-06 15:23:09,Tweetbot for iΟS,879,67
107,shinkaimakoto,1102129227267170306,『秒速５センチメートル』の公開日が12年前の今日だったとのこと。当時からの観客の皆さま、本当...,141,2019-03-03 08:50:59,Tweetbot for Mac,9293,2432
108,shinkaimakoto,1102054729062920192,"korea, too? Thank you for your warm support. h...",112,2019-03-03 03:54:57,Tweetbot for Mac,236,26
109,shinkaimakoto,1102053329880801281,雨の日曜ですね。雨の音を聞きながら作っています。 https://t.co/BRVC0z3vMT,48,2019-03-03 03:49:23,Tweetbot for iΟS,2640,308
110,shinkaimakoto,1102051631330320385,「新海誠展」いよいよ本日最終日とのこと。２年間熱心に支えてくださった各地のスタッフの皆さま、...,137,2019-03-03 03:42:38,Tweetbot for Mac,926,181
111,ByronPHoward,1103186538693779456,@jrsygrl281 That’s really sweet 😊,33,2019-03-06 06:52:21,Twitter for iPhone,2,0
112,ByronPHoward,1103071089570115585,A vertical version of yesterday's thank-you #Z...,188,2019-03-05 23:13:36,Twitter Web App,1115,237
113,ByronPHoward,1102614089451266049,RT @thejaredbush: It’s bananas that #Zootopia ...,139,2019-03-04 16:57:39,Twitter Web App,0,63
114,ByronPHoward,1102587222253961217,A little piece I did... To the amazingly talen...,266,2019-03-04 15:10:53,Twitter for iPhone,5706,1516
115,ByronPHoward,1102321240277045248,Tomorrow... maybe a little something #Zootopia...,128,2019-03-03 21:33:58,Twitter for iPhone,922,223
116,lennyabrahamson,1103322244321820672,RT @jvplive: Jewish Voice for Peace supports @...,140,2019-03-06 15:51:36,Twitter for iPhone,0,141
117,lennyabrahamson,1103306080145297409,RT @Emmahnorton: Friends - Rosie is screening ...,140,2019-03-06 14:47:22,Twitter for iPhone,0,7
118,lennyabrahamson,1103089305382211585,@olwenfouere @FieldDayCompany What a wonderful...,55,2019-03-06 00:25:59,Twitter for iPad,4,0
119,lennyabrahamson,1103053288117817344,"RT @alexisgoldstein: Just this weekend, Jim Jo...",140,2019-03-05 22:02:52,Twitter for iPad,0,123
120,lennyabrahamson,1103026528412200960,RT @MikeStuchbery_: I've spent the last few mo...,140,2019-03-05 20:16:32,Twitter for iPhone,0,7673

### Production Company - Tweet Data - Dataframe

In [46]:
frame_tweet_data_pc

,username_pc,Tweet_ID,Tweet,Length,Tweet_Date,Platform,Favourites,Retweets
1,Working_Title,1103322962814472192,From kid to king! 👑 Alex meets his destiny in ...,107,2019-03-06 15:54:27,Twitter for iPhone,2,0
2,Working_Title,1102617130359554050,"RT @HannaOnPrime: If anyone asks, the girl doe...",91,2019-03-04 17:09:44,Twitter for iPhone,0,6
3,Working_Title,1102594768620740611,RT @intofilm_edu: Congratulations to Rhys Robe...,140,2019-03-04 15:40:52,Twitter for iPhone,0,25
4,Working_Title,1101527583806705665,RT @HannaOnPrime: There are two sides to every...,128,2019-03-01 17:00:16,Twitter for iPhone,0,17
5,Working_Title,1101476850738651141,RT @20CenturyFoxUK: That #FridayFeeling! #KidW...,83,2019-03-01 13:38:40,Twitter for iPhone,0,7
6,20thcenturyfox,1101905005752258561,#BreakthroughMovie tickets are here!🎟 Get your...,158,2019-03-02 18:00:00,Twitter Media Studio,81,6
7,20thcenturyfox,1101648374825082880,#BreakthroughMovie tickets are now available. ...,153,2019-03-02 01:00:14,Twitter Web Client,40,7
8,20thcenturyfox,1101557718203142144,Watch the first official clip from #Breakthrou...,216,2019-03-01 19:00:00,Twitter Media Studio,65,9
9,20thcenturyfox,1101293522039140352,Get your 🎟🎟 to @SeeBreakthrough in theaters th...,115,2019-03-01 01:30:11,Twitter Media Studio,71,12
10,20thcenturyfox,1101274321849180160,RT @DeVonFranklin: Tickets are on sale now! #R...,140,2019-03-01 00:13:53,Twitter for iPhone,0,17
11,20thcenturyfox,1101905005752258561,#BreakthroughMovie tickets are here!🎟 Get your...,158,2019-03-02 18:00:00,Twitter Media Studio,81,6
12,20thcenturyfox,1101648374825082880,#BreakthroughMovie tickets are now available. ...,153,2019-03-02 01:00:14,Twitter Web Client,40,7
13,20thcenturyfox,1101557718203142144,Watch the first official clip from #Breakthrou...,216,2019-03-01 19:00:00,Twitter Media Studio,65,9
14,20thcenturyfox,1101293522039140352,Get your 🎟🎟 to @SeeBreakthrough in theaters th...,115,2019-03-01 01:30:11,Twitter Media Studio,71,12
15,20thcenturyfox,1101274321849180160,RT @DeVonFranklin: Tickets are on sale now! #R...,140,2019-03-01 00:13:53,Twitter for iPhone,0,17
16,Participant,1103346469824688128,"""I would like to play women from the real worl...",172,2019-03-06 17:27:52,Twitter Web Client,1,0
17,Participant,1103105649464946688,We are thrilled to have two stellar documentar...,226,2019-03-06 01:30:56,Twitter Web Client,0,0
18,Participant,1103057363072778240,Thanks to everyone who attended the screening ...,282,2019-03-05 22:19:03,Twitter Web Client,1,0
19,Participant,1103057361160232961,"Last week, Nobel Peace Laureate @k_satyarthi w...",309,2019-03-05 22:19:03,Twitter Web Client,8,6
20,Participant,1103009249121058816,"""It was a master class every single day. I did...",257,2019-03-05 19:07:52,Twitter Web Client,86,14
21,SummitEnt,591649276003880960,"""There will always only be you..."" - Leo Demid...",139,2015-04-24 17:05:54,Twitter Web Client,54,719
22,SummitEnt,591291422508220417,"""Murder is strictly a capitalist disease."" - M...",139,2015-04-23 17:23:55,Twitter Web Client,24,9
23,SummitEnt,590949627114885121,"""There is no murder in this country. There is ...",137,2015-04-22 18:45:45,Twitter Web Client,24,10
24,SummitEnt,590220688071372800,Is Leo a Hero? Or a Traitor to his country? To...,132,2015-04-20 18:29:12,Twitter Web Client,15,1
25,SummitEnt,589104391837220864,"Based on the best-selling novel, #Child44 is N...",126,2015-04-17 16:33:26,Twitter Web Client,12,11
26,blumhouse,1103380140510208000,They won't stop until they kill us... or we ki...,87,2019-03-06 19:41:39,Twitter Web Client,118,21
27,blumhouse,1103365194619600896,"@Plagasx @hulu Come for @deftones, stay for th...",55,2019-03-06 18:42:16,Twitter Web Client,2,1
28,blumhouse,1103364458418597888,Great piece on how #HDD2U deals with grief in ...,90,2019-03-06 18:39:21,Twitter Web Client,41,7
29,blumhouse,1103360512681697280,"Who's ready for #SXSW? If you're at the fest, ...",174,2019-03-06 18:23:40,Twitter Web Client,26,3
30,blumhouse,1103070054743044097,Want to know what it's like to be in a writer'...,200,2019-03-05 23:09:29,Twitter Web Client,28,5
...,...,...,...,...,...,...,...,...
126,IconFilms,1103236328550998018,"1% crashes onto Digital and DVD, TODAY. Don't ...",78,2019-03-06 10:10:12,Hootsuite Inc.,6,3
127,IconFilms,1103233801373704192,The HOTEL MUMBAI team hit @DendySydney https:/...,62,2019-03-06 10:00:09,Twitter for iPhone,0,0
128,IconFilms,1103204678630686720,Great to be at @haydenorpheum for @gmaddox to ...,157,2019-03-06 08:04:26,Twitter for iPhone,3,2
129,IconFilms,1103184727631151104,LIBRARIANS ASSEMBLE!\n\nThe complete series Bo...,123,2019-03-06 06:45:09,Hootsuite Inc.,1,0
130,IconFilms,1103138157418201089,"""The songs are as infectious as the corpses th...",180,2019-03-06 03:40:06,Hootsuite Inc.,23,5
131,eldeseo,1103208160658186241,RT @sonypictures_es: Antonio Banderas protagon...,140,2019-03-06 08:18:16,Twitter for iPhone,0,8
132,eldeseo,1103208071223017472,RT @rosaliavt: El 22 de marzo se estrena “Dolo...,140,2019-03-06 08:17:55,Twitter for iPhone,0,296
133,eldeseo,1102679919283314688,RT @Version_TVE: Este domingo seguimos celebra...,140,2019-03-04 21:19:14,Twitter for iPhone,0,65
134,eldeseo,1102506512629534720,RT @antoniobanderas: Os adelanto un clip Exclu...,140,2019-03-04 09:50:10,Twitter Web Client,0,151
135,eldeseo,1101514284302065664,RT @sonypictures_es: El 22 de marzo te espera ...,140,2019-03-01 16:07:25,Twitter Web Client,0,13
136,likelystory_mcr,1101238562035400704,Really really strong @PechaKucha_MCR tonight a...,104,2019-02-28 21:51:47,Twitter for iPhone,18,2
137,likelystory_mcr,1098151407469936640,If you’ve ever used - or are currently using -...,137,2019-02-20 09:24:32,Twitter for iPhone,0,0
138,likelystory_mcr,1090558554115854336,"@ToG Thanks Toby, we’ll look into it today!",43,2019-01-30 10:33:15,Twitter for iPhone,1,0
139,likelystory_mcr,1086173277020667905,@dylanbdesigns Niiice 🤩,23,2019-01-18 08:07:44,Twitter for iPhone,1,0
140,likelystory_mcr,1080381524317556736,RT @tom_may: Why design resolutions fail - and...,140,2019-01-02 08:33:22,Twitter for iPhone,0,4
141,Archer_Gray,1103026867014111232,Excited to announce A Taste of Sky will premie...,225,2019-03-05 20:17:53,Twitter Web Client,1,0
142,Archer_Gray,1102590871378292737,Congrats to our company @SeedInvest!! https://...,61,2019-03-04 15:25:23,Twitter Web Client,1,0
143,Archer_Gray,1102248727371280385,"RT @Athenafilmfest: “If this was a man, you wo...",140,2019-03-03 16:45:50,Twitter for iPhone,0,7
144,Archer_Gray,1101227428322701313,We believe in supporting underrepresented voic...,241,2019-02-28 21:07:33,Twitter Web Client,1,2
145,Archer_Gray,1101210852659736578,Thanks to @WinstonBaker for inviting us to par...,137,2019-02-28 20:01:41,Twitter Web Client,1,0
146,DisneyAnimation,1103344718908338177,"""The only limit is your imagination."" #Wednesd...",78,2019-03-06 17:20:54,Twitter Media Studio,504,98
147,DisneyAnimation,1103012317082443776,Crowd artists on #RalphBreaksTheInternet looke...,285,2019-03-05 19:20:04,Twitter Media Studio,796,176
148,DisneyAnimation,1102978754614181888,It's a celebration in this piece of visual dev...,148,2019-03-05 17:06:42,Twitter Web Client,1041,188
149,DisneyAnimation,1102614689421262849,"Three years ago today, Zootopia was released i...",123,2019-03-04 17:00:02,Twitter Media Studio,1335,249
150,DisneyAnimation,1102584489581006849,Celebrate the third anniversary of Zootopia wi...,105,2019-03-04 15:00:02,Twitter Media Studio,3045,770
151,ElementPictures,1103360573146910725,"The White Crow, the beautiful new film from Ra...",267,2019-03-06 18:23:54,Twitter Web Client,4,0
152,ElementPictures,1103353091032784896,"RT @ScreenIreland: Described as ""the most impo...",140,2019-03-06 17:54:10,Twitter Web Client,0,6
153,ElementPictures,1103305508797235200,"RT @Rosie_Film: ★★★★ #Rosie has ""had a lot of ...",140,2019-03-06 14:45:06,Twitter for iPhone,0,3
154,ElementPictures,1103239444470161408,"RT @Rosie_Film: ★★★★ ""powered by an astonishin...",140,2019-03-06 10:22:35,Twitter for iPhone,0,5
155,ElementPictures,1102987731662262273,Ralph Fiennes will be taking part in a satelli...,310,2019-03-05 17:42:22,Twitter Web Client,2,1

### Convert Dataframes to CSV files

In [47]:
frame_final.to_csv("DMDD2_Movies.csv",sep=',',index=False)

frame_account_data_d.to_csv("DA.csv", sep=',', index=False)
frame_account_data_pc.to_csv("PA.csv", sep=',', index=False)
frame_tweet_data_d.to_csv("DT.csv",sep=',',index=False)
frame_tweet_data_pc.to_csv("PT.csv",sep=',',index=False)

## SQL Queries

In [117]:
import sqlite3
sql_con =sqlite3.connect('IMDB_Movie_Database.db')

In [118]:
frame_final.to_sql('Movies_2016_2017', con = sql_con, index=False, if_exists='replace')

In [119]:
frame_account_data_d.to_sql('Director_Acc', con = sql_con, index=False, if_exists='replace')
frame_account_data_pc.to_sql('Production_Acc', con = sql_con, index=False, if_exists='replace')
frame_tweet_data_d.to_sql('Director_Tweets', con = sql_con, index=False, if_exists='replace')
frame_tweet_data_pc.to_sql('Production_Tweets', con = sql_con, index=False, if_exists='replace')

In [120]:
def run_query(query):
    return pd.read_sql(query,sql_con)

In [112]:
#Movies_2016_2017
#run_query('SELECT * FROM Movies_2016_2017 LIMIT 5;')

In [113]:
#DA - Director_ACC
#run_query('SELECT * FROM Director_Acc LIMIT 5;')

In [114]:
#PA - Production_Acc
#run_query('SELECT * FROM Production_Acc LIMIT 5;')

In [115]:
#DT - Director_Tweets
#run_query('SELECT * FROM Director_Tweets LIMIT 10;')

In [116]:
#PT - Production_Tweets
#run_query('SELECT * FROM Production_Tweets LIMIT 5;')

### Query 1: Display all Animation movies

In [76]:
run_query('SELECT Movie,Genre FROM Movies_2016_2017 WHERE Genre LIKE "%Animation%";')

                   Movie                         Genre
0        A Monster Calls     Animation, Drama, Fantasy
1        La tortue rouge            Animation, Fantasy
2                   Sing     Animation, Comedy, Family
3  The Lego Batman Movie     Animation, Action, Comedy
4             Your Name.     Animation, Drama, Fantasy
5               Zootopia  Animation, Adventure, Comedy

### Query 2: Display Movies whose director doesn't have a Twitter account

In [79]:
run_query('SELECT Movie,D_name,username_d FROM Movies_2016_2017 WHERE username_d IS NULL;')

                          Movie                D_name username_d
0          John Wick: Chapter 2        Chad Stahelski       None
1               La tortue rouge  Michael Dudok de Wit       None
2   Kingsman: The Golden Circle        Matthew Vaughn       None
3                        Loving          Jeff Nichols       None
4         Manchester by the Sea      Kenneth Lonergan       None
5                   The Founder      John Lee Hancock       None
6                 Hacksaw Ridge            Mel Gibson       None
7                The Handmaiden        Chan-wook Park       None
8                          Love            Gaspar Noé       None
9                       Dheepan       Jacques Audiard       None
10                Hacksaw Ridge            Mel Gibson       None
11                      Mustang   Deniz Gamze Ergüven       None
12  The Diary of a Teenage Girl       Marielle Heller       None

### Query 3: Display Movie,Director and the Total_tweets by using JOIN

In [64]:
run_query('SELECT Movie,Director,Total_Tweets FROM Movies_2016_2017 left outer join Director_Acc ON Movies_2016_2017.username_d = Director_Acc.username_d;')

,Movie,Director,Total_Tweets
0,Star Wars: Episode VIII - The Last Jedi,Rian Johnson,2022.0
1,Baby Driver,Edgar Wright,34545.0
2,Hidden Figures,Theodore Melfi,8743.0
3,Logan,James Mangold,5620.0
4,A Monster Calls,J.A. Bayona,9344.0
5,John Wick: Chapter 2,Chad Stahelski,NaN
6,Get Out,Jordan Peele,4062.0
7,La tortue rouge,Michael Dudok de Wit,NaN
8,La La Land,Damien Chazelle,67.0
9,Kingsman: The Golden Circle,Matthew Vaughn,NaN
10,Moonlight,Barry Jenkins,7598.0
11,Loving,Jeff Nichols,NaN
12,Fences,Denzel Washington,86.0
13,Sing,Garth Jennings,2032.0
14,Manchester by the Sea,Kenneth Lonergan,NaN
15,Guardians of the Galaxy Vol. 2,James Gunn,20473.0
16,The Lego Batman Movie,Chris McKay,2878.0
17,The Founder,John Lee Hancock,NaN
18,Hacksaw Ridge,Mel Gibson,NaN
19,Youth,Paolo Sorrentino,10.0
20,Rippu Van Winkuru no hanayome,Shunji Iwai,53.0
21,The Handmaiden,Chan-wook Park,NaN
22,Love,Gaspar Noé,NaN
23,Elle,Paul Verhoeven,172.0
24,American Honey,Andrea Arnold,1832.0
25,Dheepan,Jacques Audiard,NaN
26,The Conjuring 2,James Wan,4126.0
27,Que Horas Ela Volta?,Anna Muylaert,2726.0
28,Hacksaw Ridge,Mel Gibson,NaN
29,Mustang,Deniz Gamze Ergüven,NaN
30,Julieta,Pedro Almodóvar,1253.0
31,Sing Street,John Carney,196.0
32,Nerve,Henry Joost,112.0
33,Your Name.,Makoto Shinkai,8063.0
34,The Diary of a Teenage Girl,Marielle Heller,NaN
35,Zootopia,Byron Howard,2938.0
36,Room,Lenny Abrahamson,13698.0

### Query 4: 10 Smallest Production Companies

In [85]:
run_query('SELECT PC_name,username_pc,Total_Tweets,Followers FROM Production_Acc ORDER BY Followers LIMIT 10 ')

                PC_Name      username_pc  Total_Tweets  Followers
0        K Period Media     KPeriodMedia            37        167
1          Likely Story  likelystory_mcr            68        352
2           Archer Gray      Archer_Gray           622        600
3   Why Not Productions       whynotprod            53        624
4             Big Beach    BigBeachFilms           753       2208
5     Illumination Ent.         IllumEnt           268       2484
6  Moho® (Anime Studio)   moho_animation          4630       5721
7           Indigo Film      indigo_film          1676       6431
8            FilmNation       filmnation          3833       7508
9            Icon Films        IconFilms          4991      12973

### Query5: Tweets Posted between length1 and length2

In [105]:
run_query('SELECT username_pc,Tweet_ID,Length FROM Production_Tweets WHERE Length BETWEEN 50 AND 60;')

     username_pc             Tweet_ID  Length
0      blumhouse  1103365194619600896      55
1  WarnerBrosEnt  1103100345872347136      51
2    indigo_film  1102358715083173889      53